### ISSUE TITLE
Theory section notes 

### ISSUE THREAD

**Issue by jthorton** [openforcefield/openff-bespokefit#129]
The following is a list of theory section notes that should be fleshed out into a full docs section. I think the main parts of the workflow are well described in the docs already so I have mainly focused on the smirks generation and parameter cache, I have included some notes on figures that might help explain some of the ideas and will add them once we agree on which ones are needed.

Do we think we should describe the features used for each cache so users can tell when bespokefit will/won't reuse results? 

tagging @SimonBoothroyd @j-wags @Yoshanuikabundi 

## Fragmentation
- Molecules are fragmented to reduce the computational cost of generating the reference QC data.
- Currently, only torsiondrives take advantage of fragmentation.
- Bespokefit can use fragmentation engines provided by openff-fragmenter directly and by default uses the WBO fragmentation method.
- In short, it builds the minimum fragment around each non-terminal rotatable bond which is electronically decoupled from the rest of the molecule by ensuring the WBO in the bond is the same in the fragment and the parent molecule. Link back to the theory in the [fragmenter docs](https://fragmenter.readthedocs.io/en/latest/index.html#wbo-sensitive-fragmentation). 

## SMIRKS Generation
- After fragmentation we can produce the bespoke SMIRKS patterns here we focus on the torsion smirks.
- We will have one fragment per rotatable bond (note some fragments may be the same if the torsions are coupled.)
- Maybe a picture of the parent molecule with rotatable bonds highlighted and arrows from the bond to the resulting fragment. Best to pick a molecule with some repeated fragments (the TYK2 series is a good example).
- Then we use [chemper](https://github.com/MobleyLab/chemper) to automatically generate new bespoke smirks patterns for each symmetry unique group of torsions that pass through the targeted central bond. 
- First, we get the atom symmetry groups using rdkit or openeye and then assign each torsion a symmetry code in the form of a tuple of atom symmetry groups corresponding to each atom in the torsion.
- Torsions are then grouped by this torsion symmetry code and a bespoke smirks pattern is made for each symmetry unique group of torsions. 
- This helps minimise the number of parameters we introduce which helps simplify the optimisation problem while still having enough degrees of freedom to achieve good accuracy.  
- Image of a fragment with the symmetry groups labelled next to another image with some symmetrical torsions highlighted. 
- Chemper is then used to generate a pattern that targets all symmetry equivalent torsions per torsion symmetry group in both the parent and fragment using the [ClusterGraph](https://github.com/MobleyLab/chemper#clustergraph) class. 
- Layers is set to `all` to ensure the maximum common substructure between the parent and fragment is encoded into the resulting bespoke smirks pattern.
- This ensures the pattern is transferable between the fragment and parent with no further modifications but also ensures it is specific enough to make sure the pattern can only be applied to other molecules which share the electronically decoupled substructure as determined by fragmenter. 
- This is important as the parameter will account for non-local effects which can not be encoded using a standard atom type approach where by parameters are stored under the combination of the atom types that make up the torsion. 
- Image of a bespoke SMIRKS pattern and with the corresponding parent and fragment molecule. The molecules should have a substructure in the SMIRKS highlighted.
- In the case of a congeneric series like the TYK2 this means that the common core need only be parameterised once, the bespoke parameters are then cached and can be reused.
- Grid image of the TYK2 series with the matched atoms highlighted from the above SMIRKS pattern.
- By default, we take a conservative approach when generating bespoke torsion parameters and expand the k terms of our reference parameter to include all periodicities from 1 to 4 ([can be changed](https://openff-bespokefit.readthedocs.io/en/latest/ref/api/openff.bespokefit/utilities/smirks/openff.bespokefit.utilities.smirks.SMIRKSettings.html#openff.bespokefit.utilities.smirks.SMIRKSettings)).
- In many cases, this is not needed and leads to redundant parameters which are held very close to the initial guess of 0 by the L1 regulariser in forcebalance.

## QC Generation
- for each molecule/fragment (only in the case of torsiondrives) and fitting target combination a QC reference data generation task is created. 
- To avoid unnecessary torsiondrive calculations this stage will only generate tasks for fragments that can not reuse any cached bespoke parameters.
- Tasks include optimisations, hessians and 1D torsiondrives. Each task is then submitted to the QC generation queue and consumed by celery workers which run the job via [QCEngine](https://github.com/MolSSI/QCEngine) thus any qcengine supported program can be used to calculate the reference data.
- Once a task has successfully completed we also cache the result for later use which can save significant time when refitting a torsion with different optimisation settings to the same reference data. 
- For high throughput bespoke parameter deviation we recommend using the fantastic [QCFracal](https://github.com/MolSSI/QCFractal) distributed computing and database for quantum chemistry. 
- Users can easily set up a local server and submit large datasets of torsiondrives using [QCSubmit](https://github.com/openforcefield/openff-qcsubmit/) which can then be used as reference data by bespokefit via the cache update feature- need a section on how to pull down qcarchive data and cache locally. 

## Optimisation
- We use the same fitting techniques to optimise the bespoke parameters as those used to make the mainline [openff force fields](https://pubs.acs.org/doi/abs/10.1021/acs.jctc.1c00571?casa_token=kcqqp1v-6yMAAAAA:e8fNPsOOOFe4oR6kBPY4dm3HJ4jC9QDZrBhb-bVGPrHu5odnxTgXUmYZXEFjiGDt5hb5Arbyf6dPxoKB).
- In short torsion parameters are optimised by minimising the RMSE difference between the QM and MM potential energy surfaces. 
- Due to limitations in the functional form of the MM force field we perform a restrained relaxation from the QM reference minimums before computing the potential energy. 
- This helps relax high energy steric clashes while the restraints keep us close to the QM minimum. 
- By default we use quite large priors on the torsion k values so we are not hindered by our initial guess parameters which are taken from the reference force field or 0 if the term was not already present. 
- Once optimisation has been completed successfully the bespoke parameters are cached so that they can be reused on any other molecule which shares this substructure provided the optimisation settings remain the same.

**Comment by j-wags** [comment]
This is great and super thorough, @jthorton. Thanks so much for putting this together!

For @Yoshanuikabundi - 
* The "TYK2 ligands" are mentioned a few times here. They're from our protein-ligand benchmark dataset, specifically in the `02_ligands` folder [here](https://github.com/openforcefield/protein-ligand-benchmark/tree/master/data/2020-02-07_tyk2.)
* There are a few concepts mentioned here that haven't been present in the other packages you worked on - Feel free to follow up either with me directly, or in this thread, on any concepts that we can explain to help you move the theory section forward (L1 regularizers, priors, or symmetry groups, etc). I'm happy to chat with you about most of them, and for the stuff I don't know, maybe folks on this thread can provide links to appropriate descriptions. 

> Do we think we should describe the features used for each cache so users can tell when bespokefit will/won't reuse results?

I don't think this should be a top priority right now - If the caching functionality is new (added in #110, I believe?) then it may be undergoing rapid changes, so we could wait for it to become a bit more battle-tested before we write prose for it.

**Comment by Yoshanuikabundi** [comment]
Hey @jthorton - these are great notes and I'm making my way through writing them up, thanks!

>- By default, we take a conservative approach when generating bespoke torsion parameters and expand the k terms of our reference parameter to include all periodicities from 1 to 4 (can be changed).
>- In many cases, this is not needed and leads to redundant parameters which are held very close to the initial guess of 0 by the L1 regulariser in forcebalance.

I have some questions about this - I think I know what you mean but I want to make sure:

- You say reference parameter, but I'm imagining the reference data to be discrete forces and energies computed at points around the torsion drive, rather than a sum of sine functions. The next point seems to be talking about the optimized parameters, so I'm guessing if you were being hyper precise you'd say you "expand the k terms of the *target* parameter", but at this point the reference data hasn't been generated yet so the two terms are kind of interchangeable - is that right?
- Are the phases expanded as well, or are they fixed?

**Comment by Yoshanuikabundi** [comment]
> For high throughput bespoke parameter deviation we recommend using the fantastic QCFracal distributed computing and database for quantum chemistry.

How does this work in practice? Does the executor have an option that I'm missing to send stuff to QCFractal, or can the workflow factory be configured to use QCFractal as a sort of QC engine, or do users need to collect batch jobs manually? We should document this clearly somewhere but I seem to have missed that this was possible for compute.

**Comment by Yoshanuikabundi** [comment]
Ahhhhh thanks Simon that makes sense.

**Comment by jthorton** [comment]
@Yoshanuikabundi sorry about the confusion but Simon is correct and that is probably a good way to phrase it in the docs with an example. 

>How does this work in practice? Does the executor have an option that I'm missing to send stuff to QCFractal, or can the workflow factory be configured to use QCFractal as a sort of QC engine, or do users need to collect batch jobs manually? 

So far the user has to submit the jobs to their own instance of QCFractal we did try to automate this is in the past but handling errors in QCFractal can be complicated. Once the jobs are complete they can use the [CLI](https://github.com/openforcefield/openff-bespokefit/blob/55c699a248ab1fad7ae3925406631e0d7f5fe29b/openff/bespokefit/cli/cache.py#L38) in bespokefit to convert the QCFractal data to a local format we can cache in redis and use. 

In future, we might want to make this even easier for the user and provide a CLI point to generate QCSubmit datasets using a list of molecules and a workflow schema which can then be submitted to a QCFractal instance by the user. We could also have the qc-generation stage search a list of QCFractal instances provided by the user for a calculation and use that rather than having the user be responsible for updating the cache using the CLI.

**Comment by Yoshanuikabundi** [comment]
Opened #137 which is my current status for this.

> sorry about the confusion but Simon is correct and that is probably a good way to phrase it in the docs with an example.

Writing this up was actually a joy, I learnt a lot looking stuff up and your notes felt detailed and comprehensive! Yeah I agree, @SimonBoothroyd's description of optimizing a super specific copy of a parameter helped me frame things in a way I really like

> So far the user has to submit the jobs to their own instance of QCFractal

How does the user get the jobs out to submit them?

I think this would be a great feature but we should hold off on recommending QCFractal here until we have a good story for integrating with it. It feels like basically recommending that users do everything by hand rather than use bespokefit. The cache CLI command looks awesome though, how often do we think people will be able to get away with existing QC data? I would've thought working on top secret IP drugs would've ruled that out for most of our users without some way of generating the data.

**Comment by jthorton** [comment]
>How does the user get the jobs out to submit them?

So far they would have to run their set of molecules through QCSubmit using the same fragmentation settings as bespokefit (they default to the same for now) and then submit them to a QCfractal instance. So that step could be better integrated with Bespokefit. 

>How often do we think people will be able to get away with existing QC data?

True they might not often have hits on the general archive but may have more luck as they build up their own local collection in a private instance. We also have a large collection of fragments in the public QCArchive from well-known free energy benchmarks which could be very helpful to users who might want to test Bespokefit so it would be good to document how they can use that data. This will also hopefully be mentioned in the publication.
