### ISSUE TITLE
About the type of QM calculations that will be performed

### ISSUE THREAD

**Issue by xiki-tempula** [openforcefield/openff-bespokefit#163]
I wonder if I could have some clarification with regard to the type of QM calculations that will be performed?
In the https://openff-bespokefit.readthedocs.io/en/latest/users/theory.html#optimization
It is said that 

```
torsion profile: the torsion profile computed by performing a torsion scan using the current force field parameters against the reference QC torsion profile.

vibrational frequency: vibrational frequencies computed from MM hessian data against those computed from reference QC hessian calculations.

optimized geometry: internal coordinates of a conformer of the molecule minimized using the current values of the force field against the same conformer minimized using QC methods.
```

So I would imagine that QM hessian will be computed.
QM geometry optimisation will be performed as part of the TorsionDrive process.

I wonder if this understanding is correct? Thank you.

**Comment by jthorton** [comment]
Hi @xiki-tempula each of these optimization targets have a corresponding QM calculation type, so if you wanted to optimise bond and angle parameters via the `vibrational frequency` target then Bespokefit would need to optimise the geometry and then compute the hessian. By default, Bespokefit will only derive bespoke torsion parameters (this is the `torsion profile` target mentioned above) and so will perform a torsion drive using the [TorsionDrive](https://github.com/lpwgroup/torsiondrive) software. This involves a series of constrained optimisations around the targeted rotatable bond. Once we fully support all of the targets then you will be able to [configure a workflow](https://openff-bespokefit.readthedocs.io/en/latest/users/bespoke-workflows.html#fitting-workflows) which uses your selection of targets from the list you quote.

**Comment by xiki-tempula** [comment]
@jthorton Thanks for the explanation.
