### ISSUE TITLE
Find OE_liscence from ~/.OpenEye/oe_license.txt

### ISSUE THREAD

**Issue by xiki-tempula** [openforcefield/openff-bespokefit#171]
It is quite common that one doesn't explicitly set the OE_LICENSE variable but puts it in the position as is mentioned in https://docs.eyesopen.com/applications/common/license.html

So it would be good to check if the `oe_license.txt` is in 
```
~USERNAME/.OpenEye
/Users/USERNAME/Library/OpenEye
~USERNAME
C:\Users\USERNAME\AppData\Local\OpenEye
```
Before saying that cannot find it.

**Comment by j-wags** [comment]
Hi @xiki-tempula - I don't think our code ever directly tries to access or locate the OpenEye license file. Instead our code communicates with the OpenEye libraries directly, and those OpenEye libraries contain all the logic for detecting a license (including the information of where to look). 

So, for example here, you would probably get the same error from running pure OpenEye code. without any OpenFF software being involved:

```python
from openeye import oechem, oequacpac, oeomega
mol = oechem.OEMol()
oechem.OESmilesToMol(mol, 'CCO')
omega = oeomega.OEOmega()
omega(mol)
oequacpac.OEAssignCharges(mol, oequacpac.OEAM1BCCCharges())
```

So I'm pretty sure this one is out of our hands, but we can reopen the issue if I'm mistaken!
