### ISSUE TITLE
Using external data

### ISSUE THREAD

**Issue by simonaxelrod** [openforcefield/openff-bespokefit#242]
Hi there,

Thanks for the great package! I really love the work you've done to make force field generation easier. I was wondering if you can use bespokefit to fit a force field with externally generated data. For example, if I have data from a neural network potential MD run, can I use that to generate a force field with bespokefit? Or, if that isn't possible or preferable, what's the easiest way to use my (non-ANI) neural network as a QC method in the standard workflow?

Thanks!

Simon

**Comment by Yoshanuikabundi** [comment]
Hi Simon, sorry for the slow response. I could be wrong (@jthorton?) but I don't think BespokeFit is really geared towards either of these use cases. We don't currently support all the interactions you'd need for a full force field, and we don't have a way of including user data in fits (or at least, not a documented one). If I'm understanding you right, you might be better off using [ForceBalance](https://leeping.github.io/forcebalance/doc/html/index.html) directly!

**Comment by simonaxelrod** [comment]
No problem! Thanks for getting back to me, and that makes sense. I'll check out ForceBalance. Another alternative might be Espaloma, since you can put whatever data you want in the training set. What do you think of that option?

**Comment by jthorton** [comment]
Hi @simonaxelrod I agree with Josh BespokeFit could be made to fit some torsion parameters from the MD snapshots but this hasn't been tested and you would probably want to fit other valence terms as well to get good performance so ForceBalance is the best bet! 

Espaloma would be interesting to try as it also lets you avoid coming up with bespoke smirks patterns for the molecule as the network also optimises the embeddings so you don't have to worry about how to split parameter types which might be too general, the fitting data should drive the model to an optimal set of parameter types.

**Comment by Yoshanuikabundi** [comment]
I also agree with Josh (:stuck_out_tongue:), Espaloma would definitely also be worth a try!

I'm closing this for triage purposes but feel free to either ask more questions here, or to open a topic in our [discussion forum](https://github.com/orgs/openforcefield/discussions)!

**Comment by simonaxelrod** [comment]
Got it, thanks so much everyone!
