### ISSUE TITLE
Using psi4 

### ISSUE THREAD

**Issue by okbckim** [openforcefield/openff-bespokefit#314]
**Description**

I am trying to use psi4 as qc program. I was able to run openff-bespoke with xtb but failed with psi4. According to the attached output, it complains s-dftd3 is not found. But I can run s-dftd3 from the commandline.

$ s-dftd3
Usage: s-dftd3 [run|param] [options] ...

**Reproduction**
openff-bespoke executor run --directory bespoke_tmp --n-fragmenter-workers 12 --n-optimizer-workers 12  --n-qc-compute-workers 12 --qc-compute-n-cores 2  --qc-compute-max-mem 3 --file ~/compute/bespoke/30.sdf --workflow "default" --default-qc-spec psi4 B3LYP-D3BJ DZVP

**Output**

[output.json](https://github.com/openforcefield/openff-bespokefit/files/13964646/output.json)

**Software versions**

- Which operating system and version are you using?
Linux lambda1 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- How did you install BespokeFit?
I followed the instruction in openff-bespoke
- Are you using Apple Silicon? If so, are you running BespokeFit in Rosetta (`osx-64`) or natively (`osx-arm64`)? No
- What is the output of running `conda list`?

<details><summary>Output of <code>conda list</code></summary><pre>

Please place the output of `conda list` here
# packages in environment at /home/bckim/mambaforge/envs/bespokefit-env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
ambertools                23.3            py310h05519df_6    conda-forge
amberutils                21.0                     pypi_0    pypi
amqp                      5.2.0              pyhd8ed1ab_1    conda-forge
anyio                     4.2.0              pyhd8ed1ab_0    conda-forge
argcomplete               3.2.1              pyhd8ed1ab_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py310h2372a71_4    conda-forge
arpack                    3.8.0           nompi_h0baa96a_101    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3              pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.7.11               h0b4cabd_1    conda-forge
aws-c-cal                 0.6.9                h14ec70c_3    conda-forge
aws-c-common              0.9.12               hd590300_0    conda-forge
aws-c-compression         0.2.17               h572eabf_8    conda-forge
aws-c-event-stream        0.4.1                h97bb272_2    conda-forge
aws-c-http                0.8.0                h9129f04_2    conda-forge
aws-c-io                  0.14.0               hf8f278a_1    conda-forge
aws-c-mqtt                0.10.1               h2b97f5f_0    conda-forge
aws-c-s3                  0.4.9                hca09fc5_0    conda-forge
aws-c-sdkutils            0.1.13               h572eabf_1    conda-forge
aws-checksums             0.1.17               h572eabf_7    conda-forge
aws-crt-cpp               0.26.0               h04327c0_8    conda-forge
aws-sdk-cpp               1.11.210            hba3e011_10    conda-forge
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
backports.zoneinfo        0.2.1           py310hff52083_8    conda-forge
basis_set_exchange        0.9.1              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
billiard                  4.2.0           py310h2372a71_0    conda-forge
bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.5               h0f2a231_0    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
brotli-python             1.1.0           py310hc6cd4ac_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.25.0               hd590300_0    conda-forge
c-blosc2                  2.12.0               hb4ffafa_0    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.3.2              pyhd8ed1ab_0    conda-forge
cairo                     1.18.0               h3faef2a_0    conda-forge
cdpkit                    1.0.2                    pypi_0    pypi
celery                    5.3.5              pyhd8ed1ab_0    conda-forge
certifi                   2023.11.17         pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py310h2fee648_0    conda-forge
chardet                   5.2.0           py310hff52083_1    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
chemper                   1.0.1              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
click-didyoumean          0.3.0              pyhd8ed1ab_0    conda-forge
click-option-group        0.5.6              pyhd8ed1ab_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
click-repl                0.3.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.1              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0           py310hd41b1e2_0    conda-forge
cuda-cudart               12.2.140             hd3aeb46_0    conda-forge
cuda-cudart_linux-64      12.2.140             h59595ed_0    conda-forge
cuda-nvrtc                12.2.140             hd3aeb46_0    conda-forge
cuda-version              12.2                 he2b69de_2    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
debugpy                   1.8.0           py310hc6cd4ac_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dftd3                     0.7.0                    pypi_0    pypi
dftd3-python              1.0.0           py310hf3546b9_1    conda-forge
dftd4                     3.5.0                    pypi_0    pypi
dkh                       1.2                  hd59d2e7_0    conda-forge
edgembar                  0.2                      pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
fastapi                   0.86.0             pyhd8ed1ab_0    conda-forge
fftw                      3.3.10          nompi_hc118613_108    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.47.2          py310h2372a71_0    conda-forge
forcebalance              1.9.6           py310hcb52e73_1    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
freetype-py               2.3.0              pyhd8ed1ab_0    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gau2grid                  2.0.7                h0b41bf4_2    conda-forge
geometric                 1.0                pyhd8ed1ab_1    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
glog                      0.6.0                h6f12383_0    conda-forge
greenlet                  3.0.3           py310hc6cd4ac_0    conda-forge
gtest                     1.14.0               h00ab1b0_1    conda-forge
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
h5py                      3.10.0          nompi_py310h65828d5_101    conda-forge
hdf4                      4.2.15               h2a13503_7    conda-forge
hdf5                      1.14.3          nompi_h4f84152_100    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  1.0.2              pyhd8ed1ab_0    conda-forge
httpx                     0.26.0             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
importlib-metadata        7.0.1              pyha770c72_0    conda-forge
importlib_metadata        7.0.1                hd8ed1ab_0    conda-forge
importlib_resources       6.1.1              pyhd8ed1ab_0    conda-forge
ipykernel                 6.28.0             pyhd33586a_0    conda-forge
ipython                   8.20.0             pyh707e725_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.8.0              pyhd8ed1ab_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.3              pyhd8ed1ab_0    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
json5                     0.9.14             pyhd8ed1ab_0    conda-forge
jsonpointer               2.4             py310hff52083_3    conda-forge
jsonschema                4.20.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.20.0             pyhd8ed1ab_0    conda-forge
jupyter-lsp               2.2.1              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.1           py310hff52083_0    conda-forge
jupyter_events            0.9.0              pyhd8ed1ab_0    conda-forge
jupyter_server            2.12.4             pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.5.1              pyhd8ed1ab_0    conda-forge
jupyterlab                4.0.10             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.25.2             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.7              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5           py310hd41b1e2_1    conda-forge
kombu                     5.3.3           py310hff52083_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20230802.1      cxx17_h59595ed_0    conda-forge
libaec                    1.1.2                h59595ed_1    conda-forge
libarrow                  14.0.2           h84dd17c_2_cpu    conda-forge
libarrow-acero            14.0.2           h59595ed_2_cpu    conda-forge
libarrow-dataset          14.0.2           h59595ed_2_cpu    conda-forge
libarrow-flight           14.0.2           h120cb0d_2_cpu    conda-forge
libarrow-flight-sql       14.0.2           h61ff412_2_cpu    conda-forge
libarrow-gandiva          14.0.2           hacb8726_2_cpu    conda-forge
libarrow-substrait        14.0.2           h61ff412_2_cpu    conda-forge
libblas                   3.9.0            20_linux64_mkl    conda-forge
libboost                  1.82.0               h6fcfa73_6    conda-forge
libboost-python           1.82.0          py310hcb52e73_6    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0            20_linux64_mkl    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcufft                  11.0.8.103           hd3aeb46_0    conda-forge
libcurl                   8.5.0                hca28451_0    conda-forge
libdeflate                1.19                 hd590300_0    conda-forge
libecpint                 1.0.7               h3ecfda7_10    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgfortran-ng            13.2.0               h69a702a_3    conda-forge
libgfortran5              13.2.0               ha4646dd_3    conda-forge
libglib                   2.78.3               h783c2da_0    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libgoogle-cloud           2.12.0               h5206363_4    conda-forge
libgrpc                   1.59.3               hd6c4280_0    conda-forge
libhwloc                  2.9.3           default_h554bfaf_1009    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libint                    2.8.1                h9bbc0ff_1    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0            20_linux64_mkl    conda-forge
libllvm15                 15.0.7               h5cf9203_3    conda-forge
libnetcdf                 4.9.2           nompi_h80fb2b6_112    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnl                     3.9.0                hd590300_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libnuma                   2.0.16               h0b41bf4_1    conda-forge
libparquet                14.0.2           h352af49_2_cpu    conda-forge
libpcm                    1.2.3                h4175798_8    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libprotobuf               4.24.4               hf27288f_0    conda-forge
libre2-11                 2023.06.02           h7a70373_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libthrift                 0.19.0               hb90f79a_1    conda-forge
libtiff                   4.6.0                ha9c0a0a_2    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libxc-c                   6.2.2            cpu_h1b64f48_4    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.11.6               h232c23b_0    conda-forge
libxslt                   1.1.37               h0054252_1    conda-forge
libzip                    1.10.1               h2629f0a_3    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvm-openmp               17.0.6               h4dfa4b3_0    conda-forge
lxml                      4.9.3           py310h9b7343a_3    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.3           py310h2372a71_1    conda-forge
matplotlib-base           3.8.2           py310h62c0568_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mctc-lib                  0.3.1                h74f4db8_0    conda-forge
mda-xdrlib                0.2.0              pyhd8ed1ab_0    conda-forge
mdtraj                    1.9.9           py310h523e8d7_1    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
mkl                       2023.2.0         h84fe81f_50496    conda-forge
mmpbsa-py                 16.0                     pypi_0    pypi
msgpack-python            1.0.7           py310hd41b1e2_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.14.1             pyhd8ed1ab_0    conda-forge
nbformat                  5.9.2              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
nest-asyncio              1.5.8              pyhd8ed1ab_0    conda-forge
netcdf-fortran            4.6.1           nompi_hacb5139_103    conda-forge
networkx                  3.2.1              pyhd8ed1ab_0    conda-forge
nglview                   3.1.1              pyh15ce09e_0    conda-forge
notebook                  7.0.6              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
numexpr                   2.8.8           mkl_py310hc8c826e_0    conda-forge
numpy                     1.26.3          py310hb13e2d6_0    conda-forge
ocl-icd                   2.3.1                h7f98852_0    conda-forge
ocl-icd-system            1.0.0                         1    conda-forge
openff-amber-ff-ports     0.0.4              pyhca7485f_0    conda-forge
openff-bespokefit         0.2.3              pyhd8ed1ab_0    conda-forge
openff-forcefields        2023.11.0          pyhca7485f_0    conda-forge
openff-fragmenter-base    0.2.0              pyhd8ed1ab_0    conda-forge
openff-interchange        0.3.10             pyhd8ed1ab_0    conda-forge
openff-interchange-base   0.3.10             pyhd8ed1ab_0    conda-forge
openff-models             0.1.1              pyhca7485f_0    conda-forge
openff-qcsubmit           0.5.0              pyhd8ed1ab_0    conda-forge
openff-toolkit            0.13.2             pyhd8ed1ab_0    conda-forge
openff-toolkit-base       0.13.2             pyhd8ed1ab_0    conda-forge
openff-units              0.2.1              pyh1a96a4e_0    conda-forge
openff-utilities          0.1.12             pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.0                h488ebb8_3    conda-forge
openmm                    8.1.1           py310h9995159_0    conda-forge
openssl                   3.2.0                hd590300_1    conda-forge
optking                   0.2.1              pyhd8ed1ab_0    conda-forge
orc                       1.9.2                h4b38347_0    conda-forge
overrides                 7.4.0              pyhd8ed1ab_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
packmol                   20.010               h86c2bf4_0    conda-forge
packmol-memgen            2023.2.24                pypi_0    pypi
pandas                    1.4.4           py310h769672d_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
panedr                    0.8.0              pyhd8ed1ab_0    conda-forge
parmed                    4.2.2           py310hc6cd4ac_1    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcmsolver                 1.2.3                      py_8    conda-forge
pcre2                     10.42                hcad00b1_0    conda-forge
pdb4amber                 22.0                     pypi_0    pypi
perl                      5.32.1          7_hd590300_perl5    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.2.0          py310h01dd4db_0    conda-forge
pint                      0.21               pyhd8ed1ab_0    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
pixman                    0.43.0               h59595ed_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.1.0              pyhd8ed1ab_0    conda-forge
plotly                    5.18.0             pyhd8ed1ab_0    conda-forge
prometheus_client         0.19.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
prompt_toolkit            3.0.42               hd8ed1ab_0    conda-forge
psi4                      1.9             py310hb14b25f_1    conda-forge
psutil                    5.9.7           py310h2372a71_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pugixml                   1.14                 h59595ed_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py-cpuinfo                9.0.0              pyhd8ed1ab_0    conda-forge
pyarrow                   14.0.2          py310hf9e7431_2_cpu    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycairo                   1.25.1          py310hda9f760_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.13         py310h2372a71_1    conda-forge
pyedr                     0.8.0              pyhd8ed1ab_0    conda-forge
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pymbar                    3.1.1           py310hde88566_2    conda-forge
pymsmt                    22.0                     pypi_0    pypi
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyscf                     2.4.0                    pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytables                  3.9.2           py310h374b01c_1    conda-forge
python                    3.10.13         hd12c33a_1_cpython    conda-forge
python-constraint         1.4.0                      py_0    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.19.1             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.4             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pytraj                    2.0.6                    pypi_0    pypi
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py310h2372a71_1    conda-forge
pyzmq                     25.1.2          py310h795f18f_0    conda-forge
qcelemental               0.27.1             pyhd8ed1ab_0    conda-forge
qcengine                  0.29.0             pyhd8ed1ab_0    conda-forge
qcportal                  0.15.8             pyhd8ed1ab_1    conda-forge
rdkit                     2023.09.4       py310hb79e901_0    conda-forge
rdma-core                 49.0                 hd3aeb46_2    conda-forge
re2                       2023.06.02           h2873b5e_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
redis-py                  5.0.1              pyhd8ed1ab_0    conda-forge
redis-server              7.2.4                h06160fa_0    conda-forge
referencing               0.32.1             pyhd8ed1ab_0    conda-forge
regex                     2023.12.25      py310h2372a71_0    conda-forge
reportlab                 4.0.9           py310h2372a71_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rich                      13.7.0             pyhd8ed1ab_0    conda-forge
rlpycairo                 0.2.0              pyhd8ed1ab_0    conda-forge
rpds-py                   0.17.1          py310hcb5633a_0    conda-forge
s2n                       1.4.1                h06160fa_0    conda-forge
sander                    22.0                     pypi_0    pypi
scipy                     1.11.4          py310hb13e2d6_0    conda-forge
send2trash                1.8.2              pyh41d4057_0    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
simple-dftd3              1.0.0                hd59d2e7_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smirnoff99frosst          1.1.0              pyh44b312d_0    conda-forge
snappy                    1.1.10               h9fff704_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
sqlalchemy                2.0.25          py310h2372a71_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
starlette                 0.20.4             pyhd8ed1ab_1    conda-forge
tbb                       2021.11.0            h00ab1b0_0    conda-forge
tenacity                  8.2.3              pyhd8ed1ab_0    conda-forge
terminado                 0.18.0             pyh0d859eb_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
toml-f                    0.4.2                hd8f1df9_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.3.3           py310h2372a71_1    conda-forge
torsiondrive              1.1.0              pyhd8ed1ab_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.1             pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.8.19.20240106    pyhd8ed1ab_0    conda-forge
typing-extensions         4.9.0                hd8ed1ab_0    conda-forge
typing_extensions         4.9.0              pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
ucx                       1.15.0               h6d2d1ec_2    conda-forge
unicodedata2              15.1.0          py310h2372a71_0    conda-forge
unidecode                 1.3.8              pyhd8ed1ab_0    conda-forge
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   2.1.0              pyhd8ed1ab_0    conda-forge
uvicorn                   0.25.0          py310hff52083_0    conda-forge
vine                      5.1.0              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
webcolors                 1.13               pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.7.0              pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.6.6              pyhd8ed1ab_0    conda-forge
xmltodict                 0.13.0             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.7                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-libxt                1.3.0                hd590300_1    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xtb                       6.5.1                h03160e7_1    conda-forge
xtb-python                22.1            py310h1fa729e_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.5                h59595ed_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zlib-ng                   2.0.7                h0b41bf4_0    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
</pre></details>

**Comment by mattwthompson** [comment]
Did you run any `pip install` commands? I notice some of the DFT packages are pulled down from PyPI instead of `conda-forge`, where I'd expect them to be from.

```
dftd3                     0.7.0                    pypi_0    pypi

dftd3-python              1.0.0           py310hf3546b9_1    conda-forge

dftd4                     3.5.0                    pypi_0    pypi

**Comment by okbckim** [comment]
Probably I tried conda install but failed to get running and tried pip install. What is the exact modules to install with conda install -c conda-forge? There is also simple-dftd3 available in conda-forge. I would like to uninstall all and reinstall with the correct way you recommend. Thank you so much!

**Comment by okbckim** [comment]
I uninstalled dftd3 related modules and reinstall using conda install -c conda-forge dftd3-python. Now I have these in conda list

dftd3-python              1.0.0           py310hf3546b9_1    conda-forge
simple-dftd3              1.0.0                hd59d2e7_0    conda-forge

But I still get the error message with following message.

 ModuleNotFoundError(\nModuleNotFoundError: Python module 'dftd3' not found in envvar PYTHONPATH. Please install a dftd3 version with
 enabled Python API (e.g. conda install dftd3-python -c conda-forge)\

**Comment by mattwthompson** [comment]
I recommend creating a new environment and starting fresh; though it may seem counter-intuitive, it is the safest way to reproduce issues (and the infrastructure is designed for rapid deployment)

There is a `dftd3-python` floating around that Psi4 1.9 may want; Psi4 generally brings its dependencies in via`conda-forge` even if some may be available on PyPI

**Comment by okbckim** [comment]
Thank you.
I created new environment with this command copied from openff-bespoke installation page

mamba create -n bespokefit -c conda-forge/label/libint_dev -c conda-forge  python=3.10 openff-bespokefit "qcportal <0.50" psi4 dftd3-python ambertools
conda activate bespokefit
BEFLOW_OPTIMIZER_KEEP_FILES=True openff-bespoke executor run --directory bespoke_tmp --n-fragmenter-workers 12 --n-optimizer-workers 12  --n-qc-compute-workers 12 --qc-compute-n-cores 2  --qc-compute-max-mem 3 --file ~/compute/bespoke/30.sdf --workflow "default" --default-qc-spec psi4 B3LYP-D3BJ DZVP

I still got the same error message.

**Comment by mattwthompson** [comment]
Thanks - I think this is likely to be a case in which the installation instructions are slightly out of date. There were some changes with Psi4 1.9 that I'm only familiar with at a surface level, but (as I understand it) are supposed to automagically find the best DFT package it can interface with.

I don't immediately have time to test this, but the first thing I would try is `mamba create -n bespokefit -c conda-forge python=3.10 openff-bespokefit "qcportal <0.50" psi4 ambertools` and checking to see
* Is Psi4 1.8 or 1.9 brought down? I expect 1.9
* What DFT packages are brought it? I think `dftd4-python` or something like that should be brought in, from `conda-forge`
* Does the same crash occur? (Psi4 crashing when not finding a DFT package/executable it expects)

**Comment by okbckim** [comment]
I simply removed  --directory bespoke_tmp from the above command. Now psi4 are running in this stage
⠸ generating bespoke QC data

Unexpected consequence but it is good things are running. I will update the case with the result. 
Thank you so much!

**Comment by mattwthompson** [comment]
Great news - I should have caught that earlier

**Comment by okbckim** [comment]
NP. Using --directory option, I would like to monitor the progress. Without the option, the bespoke job seems to use /tmp. It is hard to grasp what is going on. Is there any options to get more details job progress info?

The job is still running submit with following options, --n-fragmenter-workers 12 --n-optimizer-workers 12 --n-qc-compute-workers 12 --qc-compute-n-cores 2 --qc-compute-max-mem 3. I observed there were 8 psi4 jobs running on 2 cores earlier. Actually my test molecule is composed of 8 rotatable bonds. Maybe that's a reason to run 8 psi4 jobs? Now there are two psi4 jobs still running. The bespoke job has been running for 20 hours so far. Is this speed consistent with what you estimate?

Thank you again for the response!

**Comment by okbckim** [comment]
Thank you for pointing the documents. It looks like python API is a way to control the workflow in detail.
You can close this issue. Thank you again for the helpful tips.
