### ISSUE TITLE
Document environment variables

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-bespokefit#326]
**Description**

There are a some number of environment variables that BespokeFit may interpret. These need to be documented in a more user-facing way, i.e. without reading through #199 I wouldn't think of using `BEFLOW_OPTIMIZER_KEEP_FILES`, which is otherwise buried in [API docs generated from the source code]( https://docs.openforcefield.org/projects/bespokefit/en/latest/ref/api/openff.bespokefit/executor/services/openff.bespokefit.executor.services.Settings.html#openff.bespokefit.executor.services.Settings.BEFLOW_OPTIMIZER_KEEP_FILES)

**Comment by Yoshanuikabundi** [comment]
We [used to](https://docs.openforcefield.org/projects/bespokefit/en/0.1.3/users/bespoke-executor.html#configuring-from-the-environment) have this. I'll fix it.

**Comment by mattwthompson** [comment]
Awesome, I think that's exactly what I was looking for!

Where are the files meant to be saved? Just in the local path? I was in a development environment so I could have broken something

**Comment by Yoshanuikabundi** [comment]
They should be saved in the scratch directory - by default this is a temporary directory, but you can change it to wherever you want with the `--directory` argument

**Comment by mattwthompson** [comment]
Perfect - that's the detail I was missing
