### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-bespokefit#354]
**Description**
[Tests are failing](https://github.com/openforcefield/openff-bespokefit/actions/runs/9965845554/job/27536871830#step:8:158
) on `openff/bespokefit/_tests/executor/services/fragmenter/test_worker.py::test_fragment_mock`

I'm able to reproduce this locally on an M1 macbook running OSX 14.

I'm able to reproduce what I believe is the root issue using just the OpenFF Toolkit - Working on resolving that in https://github.com/openforcefield/openff-toolkit/issues/1909

**Comment by mattwthompson** [comment]
#355
