### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-bespokefit#362]
**Description**

When running CI using micromamba, tests fail

* at `openff/bespokefit/_tests/executor/services/coordinator/test_app.py::test_get_molecule_image` when testing WITHOUT OpenEye
* at `openff/bespokefit/_tests/executor/utilities/test_depiction.py::test_smiles_to_image[_rd_smiles_to_image]` when testing WITH openeye

**Reproduction**

This reproduces locally when building the dev env using micromamba with mamba `1.5.7` (but NOT when building it with vanilla mamba `1.5.1`)

**Comment by mattwthompson** [comment]
FTR, setting memory limits seems to smooth over many issues like this. Look at #375 for a starting point of just one of these flags
