### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by jthorton** [openforcefield/openff-bespokefit#6]
To help demonstrate all of the features of bespokefit we need some example notebooks/tutorials (look at evaluator/toolkit) for the inspiration they should be quick to run and give a general overview of the use of the project.

**Comment by SimonBoothroyd** [comment]
@jthorton I think we can close this for now as we've started including these into the docs directly? Re-open if not the case though!

Maybe we should open specific issues if there a parts of the code base where extra examples in the docs would be useful?
