### ISSUE TITLE
Consider adding a `--smiles` option to the CLI

### ISSUE THREAD

**Issue by Yoshanuikabundi** [openforcefield/openff-bespokefit#99]
Over in Toolkit land, we often document preferring a SMILES string to a coordinate file, as it makes it harder to make mistakes where the molecular graph is misinterpreted. Consistent with that, it would be good if we could add a `--smiles` option to the CLI that can be used in place of `--input` to provide the target molecule.

**Comment by jthorton** [comment]
@Yoshanuikabundi great idea this was added in #107 `--input` was also renamed to `--file`.
